name: Mailer Microservices CI
on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

# Both workflows should have the same concurrency group
concurrency:
  group: mailer-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true  # Automatically cancel queued workflows


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"
      
      - name: Install dependency
        run: |
          go mod download

      - name: Cache Go modules
        id: cache-go-modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-        
        
      - name: Build
        run: |
          cd cmd/mailer
          go build -o expenses .

      - name: unit tests
        run: |
          cd cmd/mailer
          go test 

  code-quality:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"

      - name: Restore Go modules cache
        id: cache-go-modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-  

      - name: Install dependencies
        if: steps.cache-go-modules.outputs.cache-hit != 'true'
        run: |
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8 
        with:
          version: v2.1
          args: golangci-lint run
          working-directory: cmd/mailer
        continue-on-error: true

  container:
    runs-on: ubuntu-latest
    needs: [build, code-quality]

    steps:
      - name: checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (local only)
        run: |
          docker build -t "${{ vars.DOCKERHUB_USERNAME }}/mailer:${{ github.run_id }}" .

      - name: Scan image in a private registry
        id: trivy-scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/mailer:${{ github.run_id }} 
          scan-type: image
          severity: 'CRITICAL'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          scanners: 'vuln,secret'

      - name: Push Docker images
        # Only push if the scan was successful
        if: steps.trivy-scan.outcome == 'success'
        run: docker push "${{ vars.DOCKERHUB_USERNAME }}/mailer:${{ github.run_id }}"

  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: container
    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Checkout K8s manifest repository
        uses: actions/checkout@v4
        with:
          repository: cloudhein/flextrack-microservices
          ref: main  # or your target branch
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # PAT with repo access
          path: flextrack-repo  # Checkout to subdirectory & used in multiple repo checkout

      - name: Verify files exist
        run: |
          echo "Checking directory structure:"
          ls -la flextrack-repo/flextrack-local-kind/
          echo "Looking for mailer.yaml:"
          ls -la flextrack-repo/flextrack-local-kind/mailer.yaml

      - name: Update Kubernetes manifest
        run: |
          # Update the manifest file in the k8s-manifests directory
          sed -i "s|image: .*|image: ${{ vars.DOCKERHUB_USERNAME }}/mailer:${{ github.run_id }}|g" flextrack-repo/flextrack-local-kind/mailer.yaml 

      - name: Commit and push changes to K8s repo
        working-directory: flextrack-repo/flextrack-local-kind
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add mailer.yaml 
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "[CI] Update mailer image to ${{ github.run_id }} from ${{ github.repository }} [skip ci]"
            git push origin main  # or your target branch
          fi